// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uawkfwpkyrtzddmkxdzw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVhd2tmd3BreXJ0emRkbWt4ZHp3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0NTExMjUsImV4cCI6MjA2MjAyNzEyNX0.k0klnWcj-DYjwBqdZbqLLB7vLgx_2E76Mv5GCaTyu9I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);